# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160116_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='active',
            field=models.BooleanField(help_text='Turn off to hide from UI.', default=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='client',
            name='category_key',
            field=models.CharField(blank=True, null=True, help_text='Category for Richard', max_length=30),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='client',
            name='contacts',
            field=models.CharField(help_text='emails of people putting on the event.', blank=True, max_length=300),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='client',
            name='credits',
            field=models.CharField(help_text='added to end, store in assets dir', blank=True, default='ndv-169.png', max_length=30),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='client',
            name='host_user',
            field=models.CharField(blank=True, null=True, help_text='depricated - do not use.', max_length=30),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='client',
            name='postroll',
            field=models.CharField(help_text='name of video to postpend (not implemented)', blank=True, max_length=335),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='client',
            name='preroll',
            field=models.CharField(help_text='name of video to prepend (not implemented)', blank=True, max_length=335),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.CharField(help_text='dir name to store input files', blank=True, max_length=135),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='client',
            name='template_mlt',
            field=models.CharField(null=True, help_text='template to make cutlist mlt from.', default='template.mlt', max_length=60),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='client',
            name='title_svg',
            field=models.CharField(null=True, help_text='template for event/title/authors title slide.', default='title.svg', max_length=60),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='client',
            name='youtube_id',
            field=models.CharField(blank=True, null=True, help_text='key to lookup user/pw/etc from pw store', max_length=10),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cut_list',
            name='end',
            field=models.CharField(help_text='offset from start in HH:MM:SS.ss', blank=True, max_length=11),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cut_list',
            name='start',
            field=models.CharField(help_text='offset from start in HH:MM:SS.ss', blank=True, max_length=11),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='episode',
            name='active',
            field=models.BooleanField(help_text='Turn off to hide from UI.', default=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='episode',
            name='archive_mp4_url',
            field=models.CharField(blank=True, null=True, help_text='URL public can use to dl an mp4. (like archive.org', max_length=355),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='episode',
            name='archive_ogv_url',
            field=models.CharField(blank=True, null=True, help_text='URL public can use to dl an ogv (like archive.org', max_length=355),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='episode',
            name='archive_url',
            field=models.CharField(blank=True, null=True, help_text='not sure.. deprecated?', max_length=355),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='episode',
            name='channelcopy',
            field=models.CharField(blank=True, null=True, help_text='m=mono, 01=copy left to right, 10=right to left.', max_length=2),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='episode',
            name='comment',
            field=models.TextField(help_text='production notes', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='episode',
            name='conf_key',
            field=models.CharField(help_text='primary key of event in conference system database.', blank=True, max_length=32),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='episode',
            name='conf_meta',
            field=models.TextField(blank=True, null=True, help_text='Data provided by API', default=''),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='episode',
            name='conf_url',
            field=models.CharField(help_text="Event's details on conference site  (name,desc,time,author,files,etc)", blank=True, default='', max_length=335),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=models.TextField(help_text='markdown', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='episode',
            name='duration',
            field=models.CharField(blank=True, null=True, help_text='length in hh:mm:ss', max_length=15),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='episode',
            name='edit_key',
            field=models.CharField(blank=True, null=True, help_text='key to allow unauthenticated users to edit this item.', default='79053111', max_length=32),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='episode',
            name='emails',
            field=models.TextField(blank=True, null=True, help_text='email(s) of the presenter(s)'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='episode',
            name='end',
            field=models.DateTimeField(help_text='(calculated if start and duration are set.)', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='episode',
            name='hidden',
            field=models.NullBooleanField(help_text='hidden (does not show up on public episode list'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='episode',
            name='host_url',
            field=models.CharField(blank=True, null=True, help_text='URL of page video is hosted', max_length=235),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='episode',
            name='language',
            field=models.CharField(blank=True, null=True, help_text='Spoken languge (German, English...)', max_length=20),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='episode',
            name='license',
            field=models.CharField(blank=True, null=True, help_text='see http://creativecommons.org/licenses/', default='CC BY-SA', max_length=20),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='episode',
            name='locked',
            field=models.DateTimeField(blank=True, null=True, help_text='clear this to unlock'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='episode',
            name='locked_by',
            field=models.CharField(help_text='user/process that locked.', blank=True, max_length=35),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='episode',
            name='name',
            field=models.CharField(help_text='Talk title (synced from primary source)', max_length=170),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='episode',
            name='priority',
            field=models.IntegerField(blank=True, null=True, help_text='lower may not get recorded'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='episode',
            name='public_url',
            field=models.CharField(blank=True, null=True, help_text='URL public should use (like pvo or some aggregator', max_length=335),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='episode',
            name='rax_mp4_url',
            field=models.CharField(blank=True, null=True, help_text='URL public can use to get an mp4. (like rackspace cdn', max_length=355),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='episode',
            name='released',
            field=models.NullBooleanField(help_text='has someone authorised pubication'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='episode',
            name='sequence',
            field=models.IntegerField(blank=True, null=True, help_text='process order'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='episode',
            name='slug',
            field=models.CharField(help_text='file name friendly version of name', blank=True, max_length=170),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='episode',
            name='start',
            field=models.DateTimeField(help_text='initially scheduled time from master, adjusted to match reality', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='episode',
            name='state',
            field=models.IntegerField(null=True, blank=True, choices=[(0, 'borked'), (1, 'edit'), (2, 'encode'), (3, 'push to queue'), (4, 'post'), (5, 'richard'), (6, 'review 1'), (7, 'email'), (8, 'review 2'), (9, 'make public'), (10, 'tweet'), (11, 'to-miror'), (12, 'done')], default=1),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='episode',
            name='stop',
            field=models.NullBooleanField(help_text='Stop process.py from processing anymore'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='episode',
            name='summary',
            field=models.TextField(blank=True, null=True, help_text='short'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='episode',
            name='thumbnail',
            field=models.CharField(help_text='filename.png', blank=True, max_length=135),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='episode',
            name='twitter_id',
            field=models.CharField(blank=True, null=True, help_text='Data provided by API', max_length=135),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='episode',
            name='twitter_url',
            field=models.CharField(blank=True, null=True, help_text='URL of tweet to email presenters for retweeting', max_length=135),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='image_file',
            name='filename',
            field=models.CharField(help_text='foo.png', max_length=135),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='image_file',
            name='text',
            field=models.TextField(help_text='OCRed text', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='location',
            name='active',
            field=models.BooleanField(help_text='Turn off to hide from UI.', default=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='location',
            name='channelcopy',
            field=models.CharField(help_text='audio adjustment for this room', blank=True, max_length=2),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='location',
            name='default',
            field=models.BooleanField(help_text='Adds this loc to new Clients.', default=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='location',
            name='dirname',
            field=models.CharField(help_text='path to raw files. overrieds show/slug.', blank=True, max_length=135),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='location',
            name='hours_offset',
            field=models.IntegerField(blank=True, null=True, help_text='Adjust for bad clock setting', max_length=2),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='room name', default='twist', max_length=135),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.CharField(help_text='dir name to store input files', blank=True, max_length=135),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='mark',
            name='click',
            field=models.DateTimeField(help_text='When Cut was Clicked.'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='raw_file',
            name='filename',
            field=models.CharField(help_text='filename.dv', max_length=135),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='raw_file',
            name='filesize',
            field=models.BigIntegerField(help_text='size in bytes', default=1),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='raw_file',
            name='start',
            field=models.DateTimeField(blank=True, null=True, help_text='when recorded (should agree with file name and timestamp)'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='raw_file',
            name='trash',
            field=models.BooleanField(help_text='This clip is trash', default=False),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='show',
            name='active',
            field=models.BooleanField(help_text='Turn off to hide from UI.', default=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='show',
            name='announcement_state',
            field=models.IntegerField(null=True, blank=True, choices=[(1, 'preview'), (2, 'review'), (3, 'approved')], default=2),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='show',
            name='category_key',
            field=models.CharField(blank=True, null=True, help_text='Category for Richard', max_length=30),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='show',
            name='slug',
            field=models.CharField(help_text='dir name to store input files', blank=True, max_length=135),
            preserve_default=True,
        ),
    ]
