# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20161014_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='reviewers',
            field=models.TextField(blank=True, help_text='email(s) of the reviewers(s)'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='edit_key',
            field=models.CharField(blank=True, default=main.models.generate_edit_key, help_text='key to allow unauthenticated users to edit this item.', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='name',
            field=models.CharField(help_text='Video Title (shows in video search results)', max_length=170),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='room name', max_length=135),
        ),
    ]
