# Generated by Django 4.1.7 on 2023-03-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170820_0105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cut_list',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='hidden',
            field=models.BooleanField(blank=True, help_text='hidden (does not show up on public episode list', null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='released',
            field=models.BooleanField(default=False, help_text='has someone authorised pubication'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='slug',
            field=models.CharField(blank=True, help_text='file name friendly version of name', max_length=135),
        ),
        migrations.AlterField(
            model_name='episode',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'borked'), (1, 'edit'), (2, 'encode'), (3, 'push to queue'), (4, 'post'), (5, 'richard'), (6, 'review 1'), (7, 'email'), (8, 'review 2'), (9, 'make public'), (10, 'tweet'), (11, 'to-miror'), (12, 'conf'), (13, 'done')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='stop',
            field=models.BooleanField(default=False, help_text='Stop process.py from processing anymore'),
        ),
        migrations.AlterField(
            model_name='image_file',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='log',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quality',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='raw_file',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='show',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='show',
            name='locations',
            field=models.ManyToManyField(blank=True, limit_choices_to={'active': True}, to='main.location'),
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
