# Generated by Django 4.1.7 on 2023-03-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_location_options_alter_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='hidden',
            field=models.BooleanField(help_text='hidden (does not show up on public episode list', null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='released',
            field=models.BooleanField(help_text='has someone authorised pubication', null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='stop',
            field=models.BooleanField(default=False, help_text='Stop process.py from processing anymore', null=True),
        ),
    ]
