# Generated by Django 4.1.7 on 2023-10-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_episode_hidden_alter_episode_released_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='command',
            field=models.CharField(blank=True, max_length=135),
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.FloatField(blank=True, help_text='90=North Pole', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lon',
            field=models.FloatField(blank=True, help_text='US is negative', null=True),
        ),
    ]
