#!/usr/bin/python

# email_url.py
# emails the video URL to the presenters

from django.core.mail import get_connection, EmailMessage

from process import process

class email_url(process):

    ready_state = 5

    def process_ep(self, ep):
        if self.options.verbose: print ep
        if ep.emails and ep.released and ep.public_url:
            tos = ep.emails.split(',')
            subject = "Video up: %s" % ep.name
            body = """
    The video of your talk is posted:
    %(public_url)s

    Look at it, make sure I spelled everything right, let me know if it is OK.
    
    Tweet it, blog it, whatever it.  No point in making videos if no one watches them.

    Notes: PyVideo.org is a new site.  It is taking the place of python.mirocommunity.org, read about it: http://bluesock.org/~willg/blog/pmc/pyvideo_is_live and http://bluesock.org/~willg/blog/pmc/pycon_2012
    
    Email generated by Veyepar, but replies go to Carl.
    """ % ({'public_url':ep.public_url})

     
            # connect to the smtp server
            connection = get_connection()
            sender = 'Carl Karsten <carl@nextdayvideo.com>'
            headers = {
                # 'Reply-To': "ChiPy <chicago@python.org>"
                # 'From': sender,
                }    
            email = EmailMessage(subject, body, sender, tos, headers=headers ) 
            ret = connection.send_messages([email])
            print tos, ret
            ret = True # need to figure out what .send_messages returns

        else:
            ret = False
        return ret

if __name__ == '__main__':
    p=email_url()
    p.main()

