#!/usr/bin/python

# email_url.py
# emails the video URL to the presenters

from django.core.mail import get_connection, EmailMessage

from process import process

class email_url(process):

    ready_state = 6

    def process_ep(self, ep):
        if self.options.verbose: print ep
        if not ep.emails:
            ret = False
        else:
            tos = ep.emails.split(',')
            subject = "Video up: %s" % ep.name
            body = """
    The video of your talk is posted:
    %s

    Look at it, make sure I spelled everything right, let me know if it is OK.

    Tweet it, blog it, whatever it.  No point in making videos if no one watches them.
    
    Email generated by Veyepar, but replies go to Carl.
    """ % ep.host_url

     
            # connect to the smtp server
            connection = get_connection()
            sender = 'Carl Karsten <carl@nextdayvideo.com>'
            headers = {
                # 'Reply-To': "ChiPy <chicago@python.org>"
                # 'From': sender,
                }    
            email = EmailMessage(subject, body, sender, tos, headers=headers ) 
            ret = connection.send_messages([email])
            print tos, ret
            ret = True # need to figure out what .send_messages returns

        return ret

if __name__ == '__main__':
    p=email_url()
    p.main()

